//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 11:20:27 AM EST 
//


package com.bionlp.ctgov;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for certain_agreements_struct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="certain_agreements_struct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pi_employee" type="{}pi_employee_enum" minOccurs="0"/>
 *         &lt;element name="restrictive_agreement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "certain_agreements_struct", propOrder = {
    "piEmployee",
    "restrictiveAgreement"
})
public class CertainAgreementsStruct {

    @XmlElement(name = "pi_employee")
    @XmlSchemaType(name = "string")
    protected PiEmployeeEnum piEmployee;
    @XmlElement(name = "restrictive_agreement")
    protected String restrictiveAgreement;

    /**
     * Gets the value of the piEmployee property.
     * 
     * @return
     *     possible object is
     *     {@link PiEmployeeEnum }
     *     
     */
    public PiEmployeeEnum getPiEmployee() {
        return piEmployee;
    }

    /**
     * Sets the value of the piEmployee property.
     * 
     * @param value
     *     allowed object is
     *     {@link PiEmployeeEnum }
     *     
     */
    public void setPiEmployee(PiEmployeeEnum value) {
        this.piEmployee = value;
    }

    /**
     * Gets the value of the restrictiveAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictiveAgreement() {
        return restrictiveAgreement;
    }

    /**
     * Sets the value of the restrictiveAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictiveAgreement(String value) {
        this.restrictiveAgreement = value;
    }

}
